from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    TestimonialListView,
    
)

# Create a router for viewsets
router = DefaultRouter()
# router.register(r'projects', ProjectViewSet, basename='project')

# API endpoints
urlpatterns = [
    # ViewSet routes (automatically generated by router)
    path('', include(router.urls)),
    
    # List views
    path('testimonials/', TestimonialListView.as_view(), name='testimonial-list'),
    # path('logos/', ClientLogoListView.as_view(), name='clientlogo-list'),
]
