# Generated by Django 4.2.11 on 2026-04-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restructure_client_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientLogo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_logo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='brand',
            field=models.ForeignKey(help_text='Brand this project is associated with', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.brand'),
        ),
    ]
