# Generated by Django 4.2.11 on 2026-05-05 09:36

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def populate_brand_slugs(apps, schema_editor):
    Brand = apps.get_model('core', 'Brand')
    used_slugs = set()

    for brand in Brand.objects.select_related('client').order_by('id'):
        base_slug = slugify(f"{brand.client.name} {brand.name}") or f"brand-{brand.id}"
        slug = base_slug
        index = 2

        while slug in used_slugs or Brand.objects.exclude(pk=brand.pk).filter(slug=slug).exists():
            slug = f"{base_slug}-{index}"
            index += 1

        brand.slug = slug
        brand.save(update_fields=['slug'])
        used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_clientlogo_remove_project_client_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='caption',
            field=models.CharField(blank=True, help_text='Short brand summary shown on client pages', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='execution',
            field=models.TextField(blank=True, help_text='How the brand work was executed'),
        ),
        migrations.AddField(
            model_name='brand',
            name='objective',
            field=models.TextField(blank=True, help_text='Brand objective or campaign brief'),
        ),
        migrations.AddField(
            model_name='brand',
            name='outcome',
            field=models.TextField(blank=True, help_text='Outcome or achievement from the brand work'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug (auto-generated if not provided)', max_length=240),
        ),
        migrations.RunPython(populate_brand_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug (auto-generated if not provided)', max_length=240, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='achievement',
            field=models.TextField(blank=True, help_text='Results or achievement for this client'),
        ),
        migrations.AddField(
            model_name='client',
            name='caption',
            field=models.CharField(blank=True, help_text='Short line describing what the client company does', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text='Client company logo shown on the homepage and clients page', null=True, upload_to='client_logos/'),
        ),
        migrations.AddField(
            model_name='client',
            name='objective',
            field=models.TextField(blank=True, help_text="The client's overall objective or brief"),
        ),
        migrations.AddField(
            model_name='client',
            name='stores_activated',
            field=models.CharField(blank=True, help_text="Activation footprint, e.g. '120 stores' or 'Nairobi and Mombasa'", max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='team_size',
            field=models.CharField(blank=True, help_text='Team size used for the client work', max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='work_done',
            field=models.TextField(blank=True, help_text='What Braymell did for this client'),
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.brand')),
            ],
            options={
                'verbose_name': 'Brand Image',
                'verbose_name_plural': 'Brand Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
