# Generated by Django 4.2.11 on 2026-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brand_caption_brand_execution_brand_objective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AlterField(
            model_name='brand',
            name='caption',
            field=models.TextField(blank=True, help_text='Short brand summary shown on client pages'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='brandimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='caption',
            field=models.TextField(blank=True, help_text='Short line describing what the client company does'),
        ),
        migrations.AlterField(
            model_name='client',
            name='stores_activated',
            field=models.TextField(blank=True, help_text="Activation footprint, e.g. '120 stores' or 'Nairobi and Mombasa'"),
        ),
        migrations.AlterField(
            model_name='client',
            name='team_size',
            field=models.TextField(blank=True, help_text='Team size used for the client work'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
